=== spalaukou/task06/data/tours.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tours"
        xmlns:tns="http://www.example.com/tours"
        elementFormDefault="qualified">

    <element name="tours">
        <complexType>
            <sequence>
                <element name="touristVoucher"
                         type="tns:touristVoucher"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="touristVoucher">
        <sequence>
            <element name="type" type="tns:type" />
            <element name="country" type="string" />
            <element name="city" type="string" />
            <element name="numberNights" type="positiveInteger" />
            <element name="transport" type="tns:transport" />
            <element name="hotelCharacteristics" type="tns:hotelCharacteristics" />
            <element name="cost" type="tns:price" />
        </sequence>
        <attribute name="id" type="tns:id" use="required" />
    </complexType>

    <simpleType name="type">
        <restriction base="string">
            <enumeration value="rest"/>
            <enumeration value="excursion"/>
            <enumeration value="weekend"/>
            <enumeration value="gastroTour"/>
            <enumeration value="pilgrimage"/>
        </restriction>
    </simpleType>

    <simpleType name="transport">
        <restriction base="string">
            <enumeration value="car"/>
            <enumeration value="bus"/>
            <enumeration value="railway"/>
            <enumeration value="flight"/>
        </restriction>
    </simpleType>

    <complexType name="hotelCharacteristics">
        <sequence>
            <element name="stars" type="tns:first5Positive" />
            <element name="meals" type="tns:meals" />
            <element name="persons" type="positiveInteger" />
            <element name="TV" type="tns:presence" />
            <element name="condition" type="tns:presence" />
            <element name="pool" type="tns:presence" />
            <element name="freeWiFi" type="tns:presence" />
        </sequence>
    </complexType>
    <simpleType name="first5Positive">
        <restriction base="positiveInteger">
            <maxInclusive value="5"/>
        </restriction>
    </simpleType>
    <simpleType name="meals">
        <restriction base="string">
            <enumeration value="BB"/>
            <enumeration value="HB"/>
            <enumeration value="FB"/>
            <enumeration value="AI"/>
            <enumeration value="UAI"/>
        </restriction>
    </simpleType>
    <simpleType name="presence">
        <restriction base="string">
            <enumeration value="-"/>
            <enumeration value="+"/>
        </restriction>
    </simpleType>

    <complexType name="price">
        <simpleContent>
            <extension base="decimal">
                <attribute name="currency" type="tns:currency" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
    <simpleType name="currency">
        <restriction base="string">
            <enumeration value="USD"/>
            <enumeration value="EUR"/>
            <enumeration value="BP"/>
            <enumeration value="BYN"/>
            <enumeration value="RUB"/>
            <enumeration value="UAH"/>
        </restriction>
    </simpleType>

    <simpleType name="id">
        <restriction base="ID">
            <pattern value="([A-Z]){3}[0-9]{3}"/>
        </restriction>
    </simpleType>




</schema>

=== spalaukou/task06/data/tours.xml
<tours xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/tours"
        xsi:schemaLocation="http://www.example.com/tours tours.xsd">
    <touristVoucher id="ESP001">
        <type>rest</type>
        <country>Spain</country>
        <city>Barcelona</city>
        <numberNights>9</numberNights>
        <transport>flight</transport>
        <hotelCharacteristics>
            <stars>4</stars>
            <meals>FB</meals>
            <persons>2</persons>
            <TV>+</TV>
            <condition>+</condition>
            <pool>+</pool>
            <freeWiFi>+</freeWiFi>
        </hotelCharacteristics>
        <cost currency="BP">1800.00</cost>
    </touristVoucher>

    <touristVoucher id="TUR001">
        <type>excursion</type>
        <country>Turkey</country>
        <city>Antalya</city>
        <numberNights>6</numberNights>
        <transport>bus</transport>
        <hotelCharacteristics>
            <stars>5</stars>
            <meals>AI</meals>
            <persons>2</persons>
            <TV>+</TV>
            <condition>+</condition>
            <pool>+</pool>
            <freeWiFi>-</freeWiFi>
        </hotelCharacteristics>
        <cost currency="USD">1600.00</cost>
    </touristVoucher>

    <touristVoucher id="UKR001">
        <type>weekend</type>
        <country>Ukraine</country>
        <city>Lviv</city>
        <numberNights>4</numberNights>
        <transport>railway</transport>
        <hotelCharacteristics>
            <stars>3</stars>
            <meals>HB</meals>
            <persons>2</persons>
            <TV>+</TV>
            <condition>-</condition>
            <pool>-</pool>
            <freeWiFi>+</freeWiFi>
        </hotelCharacteristics>
        <cost currency="EUR">300.00</cost>
    </touristVoucher>
</tours>
